# Generated by Django 3.1.1 on 2020-09-29 15:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GhostPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_post', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=30)),
                ('body', models.CharField(max_length=280)),
                ('up_votes', models.IntegerField(default=0)),
                ('down_votes', models.IntegerField(default=0)),
                ('secret', models.CharField(max_length=7)),
                ('score', models.IntegerField(blank=True, default=0, editable=False, null=True)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
