# Generated by Django 3.1.1 on 2020-09-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghostpost',
            name='secret',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
