# Generated by Django 3.1.1 on 2020-09-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200929_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghostpost',
            name='type_of_post',
            field=models.CharField(choices=[('B', 'Boast'), ('R', 'Roast')], default='B', max_length=2),
        ),
    ]
